#!/usr/bin/env node
const commonformCommonmark = require('commonform-commonmark')
const revedCompare = require('reviewers-edition-compare')
const revedSpell = require('reviewers-edition-spell')
const commonmark = require('commonmark')
const ejs = require('ejs')
const fs = require('fs')
const glob = require('glob')
const grayMatter = require('gray-matter')
const hash = require('commonform-hash')
const path = require('path')
const rimraf = require('rimraf')
const runParallelLimit = require('run-parallel-limit')
const runSeries = require('run-series')

const BASE_HREF = 'https://stonecutters.law'

const clauses = {}
const templates = {}

runSeries([
  readClauses,
  readTemplates,
  deleteSiteDirectory,
  recreateSiteDirectory,
  copyStaticFiles,
  writeClausePages,
  writeAboutPages,
  writeHomePage
], (error) => {
  if (error) {
    console.error(error)
    process.exit(1)
  }
  process.exit(0)
})

function readClauses (done) {
  glob(path.join('clauses', '*'), (error, clauseDirectories) => {
    if (error) return done(error)
    runSeries(clauseDirectories.map(clauseDirectory => done => {
      glob(path.join(clauseDirectory, '*'), (error, editionDirectories) => {
        if (error) return done(error)
        const editions = editionDirectories
          .map(directory => path.basename(directory))
          .sort((a, b) => revedCompare(b, a))
        const latest = editions[0]
        const onlyEdition = editions.length === 1
        runSeries(editionDirectories.map(editionDirectory => done => {
          const [_, identifier, edition] = editionDirectory.split(path.sep)
          if (!clauses[identifier]) {
            clauses[identifier] = {
              identifier,
              editions: {}
            }
          }
          const record = clauses[identifier].editions[edition] = {
            spelled: revedSpell(edition)
          }
          runSeries([
            readTerms,
            readNotes,
            readCommentary
          ], done)

          function readTerms (done) {
            fs.readFile(
              path.join(editionDirectory, 'terms.md'),
              'utf8',
              (error, read) => {
                if (error) return done(error)
                const parts = grayMatter(read)
                record.identifier = identifier
                record.edition = edition
                record.latest = latest
                record.onlyEdition = onlyEdition
                record.permalink = `${BASE_HREF}/${identifier}/${edition}`
                record.editionSpelled = revedSpell(edition)
                record.frontMatter = parts.data || {}
                record.markup = parts.content
                record.parsed = commonformCommonmark.parse(record.markup)
                record.digest = hash(record.parsed.form)
                record.termsHTML = renderCommonMark(record.markup)
                done()
              }
            )
          }

          function readNotes (done) {
            readCommonMarkFile('notes.md', 'notes', done)
          }

          function readCommentary (done) {
            readCommonMarkFile('commentary.md', 'commentary', done)
          }

          function readCommonMarkFile (basename, key, done) {
            fs.readFile(
              path.join(editionDirectory, basename),
              'utf8',
              (error, read) => {
                if (error) {
                  if (error.code === 'ENOENT') {
                    record[key] = false
                    return done()
                  }
                  return done(error)
                }
                record[key] = read
                record[`${key}HTML`] = renderCommonMark(read)
                done()
              }
            )
          }
        }), done)
      })
    }), done)
  })
}

function deleteSiteDirectory (done) {
  rimraf('site', done)
}

function recreateSiteDirectory (done) {
  fs.mkdir('site', done)
}

function readTemplates (done) {
  glob(path.join('templates', '*'), (error, files) => {
    if (error) return done(error)
    runSeries(files.map(file => done => {
      const name = path.basename(file, '.ejs')
      fs.readFile(file, 'utf8', (error, template) => {
        if (error) return done(error)
        templates[name] = ejs.compile(template, {
          filename: file
        })
        done()
      })
    }), done)
  })
}

function copyStaticFiles (done) {
  glob(path.join('static', '*'), (error, files) => {
    if (error) return done(error)
    runParallelLimit(files.map(file => done => {
      const basename = path.basename(file)
      fs.copyFile(file, path.join('site', basename), done)
    }), 3, done)
  })
}

function writeClausePages (done) {
  const identifiers = Object.keys(clauses)
  runSeries(identifiers.map(identifier => done => {
    const editions = Object.keys(clauses[identifier].editions)
      .sort((a, b) => revedCompare(b, a))
    runSeries([
      createDirectory,
      writeIndex,
      writeEditions
    ], done)

    function createDirectory (done) {
      fs.mkdir(path.join('site', identifier), done)
    }

    function writeIndex (done) {
      writeTemplate(
        'clause',
        {
          identifier,
          editions: Object.keys(clauses[identifier].editions)
            .sort((a, b) => revedCompare(b, a))
            .map(edition => {
              return { code: edition, spelled: revedSpell(edition) }
            })
        },
        path.join('site', identifier, 'index.html'),
        done
      )
    }

    function writeEditions (done) {
      runParallelLimit(editions.map(edition => done => {
        writeTemplate(
          'edition',
          clauses[identifier].editions[edition],
          path.join('site', identifier, `${edition}.html`),
          done
        )
      }), 3, done)
    }
  }), done)
}

function writeAboutPages (done) {
  glob(path.join('about', '*.md'), (error, files) => {
    if (error) return done(error)
    runSeries(files.map(file => done => {
      const basename = path.basename(file, '.md')
      fs.readFile(file, 'utf8', (error, read) => {
        if (error) return done(error)
        const parts = grayMatter(read)
        const title = parts.data.title
        const markup = parts.content
        const html = renderCommonMark(markup)
        writeTemplate(
          'about',
          { title, html },
          path.join('site', `${basename}.html`),
          done
        )
      })
    }), done)
  })
}

function writeHomePage (done) {
  writeTemplate(
    'homepage',
    {
      clauses: Object.keys(clauses)
        .sort()
        .map(identifier => {
          return {
            identifier,
            edition: Object.keys(clauses[identifier].editions)
              .sort((a, b) => revedCompare(b, a))[0]
          }
        })
    },
    path.join('site', 'index.html'),
    done
  )
}

function writeTemplate (templateKey, data, file, done) {
  let html
  try {
    html = templates[templateKey](data)
  } catch (error) {
    return done(error)
  }
  fs.writeFile(file, html, done)
}

function renderCommonMark (markup) {
  const reader = new commonmark.Parser()
  const writer = new commonmark.HtmlRenderer({ safe: true })
  const parsed = reader.parse(markup)
  return writer.render(parsed)
}
